// Structured metadata for the 3 MVP letter types. The actual letter body is
// generated by Bedrock (see promptTemplate.buildLetterPrompt) using these
// field lists to prompt the user for the right details in the UI.

export const LETTER_TYPES = {
  security_deposit: {
    label: { en: "Security deposit request letter", hi: "सिक्योरिटी डिपॉज़िट वापसी पत्र" },
    fields: ["tenantName", "landlordName", "propertyAddress", "moveOutDate", "depositAmount", "daysSinceMoveOut"],
  },
  unpaid_wages: {
    label: { en: "Unpaid wages request letter", hi: "वेतन भुगतान अनुरोध पत्र" },
    fields: ["employeeName", "employerName", "companyAddress", "periodOwed", "amountOwed", "lastPaymentDate"],
  },
  consumer_complaint: {
    label: { en: "Consumer complaint letter", hi: "उपभोक्ता शिकायत पत्र" },
    fields: ["customerName", "sellerName", "productOrService", "purchaseDate", "issueDescription", "resolutionRequested"],
  },
};
